name: utp_wifi
description: "UTP WiFi"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_map: ^6.0.0
  #google_maps_flutter: ^2.5.3
  location: ^5.0.3
  #flutter_internet_speed_test: ^1.4.0
  flutter_internet_speed_test:
    git:
      url: https://github.com/luhouyang/flutter_internet_speed_test.git
  latlong2: ^0.9.0
  flutter_map_heatmap: ^0.0.7
  firebase_core: ^2.25.0
  firebase_storage: ^11.6.1
  path_provider: ^2.1.2
  flutter_map_location_marker: ^8.0.4
  animated_bottom_navigation_bar: ^1.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # assets:
    # - assets/initial_data.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

