// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJmHf_2t2NpixD4x0IVIzuPPFXxHEQ6N0',
    appId: '1:95981562376:web:251b4e8428d0e624bfbfbd',
    messagingSenderId: '95981562376',
    projectId: 'internet-heatmap',
    authDomain: 'internet-heatmap.firebaseapp.com',
    storageBucket: 'internet-heatmap.appspot.com',
    measurementId: 'G-K9H85HBGWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt-pYBPFsQXRcW57ZtdLDeuUzI-7BBtnA',
    appId: '1:95981562376:android:fd296af14d6b5277bfbfbd',
    messagingSenderId: '95981562376',
    projectId: 'internet-heatmap',
    storageBucket: 'internet-heatmap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOn7yIwXpRNYYl48UjkCDsQtHdLx6_3w8',
    appId: '1:95981562376:ios:cf44b8cc2b931162bfbfbd',
    messagingSenderId: '95981562376',
    projectId: 'internet-heatmap',
    storageBucket: 'internet-heatmap.appspot.com',
    iosBundleId: 'com.example.utpWifi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOn7yIwXpRNYYl48UjkCDsQtHdLx6_3w8',
    appId: '1:95981562376:ios:4a5970967dcda4fcbfbfbd',
    messagingSenderId: '95981562376',
    projectId: 'internet-heatmap',
    storageBucket: 'internet-heatmap.appspot.com',
    iosBundleId: 'com.example.utpWifi.RunnerTests',
  );
}
